services:
  - type: web
    name: silence-cutter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11" 