services:
  - type: web
    name: silence-cutter-api
    env: python
    plan: starter
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 